title: Ayush Modi
email: ayushmdi2003@gmail.com
description: Lorem Ipsum's website
url: "https://example.org"
twitter: ayush_modi_

baseurl: ""
permalink: /:categories/:title:output_ext
markdown: kramdown
plugins:
  - jekyll-feed